age = input("Please enter your age:\n")
print("My age is:" + age)
height = input("Please enter your height:\n")
print("My height is" + height)
print("Equal:", int(age) == float(height))
print("notEqual:", int(age) != float(height))
print("lessthen:", int(age) < float(height))
print("greaterthen:", int(age) > float(height))
print("lesstheequalto:", int(age) <= float(height))
print("greaterthenequalto:", int(age) >= float(height))