age = input("Please enter your age:\n")
print("My age is:" + age)
height = input("Please enter your height:\n")
print("My height is" + height)
print("Sum is:" , int(age) + float(height))
print("Multiply is:" , int(age) * float(height))
print("Devide is:" , int(age) / float(height))
print("Module is:" , int(age) % float(height))
print("Sub is:" , int(age) - float(height))